name: Seek Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        # Explicitly install lint tools to ensure they're available
        pip install flake8 black isort mypy
    
    - name: Lint
      run: make lint
    
    - name: Test
      run: make test
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    - name: Generate coverage report
      run: make test-cov
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
